dist: trusty
sudo: required
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev python-pip libxslt1-dev libxml2-dev
  - sudo pip install pycodestyle pylint
install:
  - sudo pip install --editable .
script:
  - pycodestyle dotheyimplement/
  - pylint dotheyimplement/
  - dotheyimplement test
